In [1]:
import pandas as pd
import numpy as np

In [2]:
feature_data = pd.read_csv(
    "../data/processed/feature_data.csv"
)

In [3]:
feature_data.head()

,Customer_ID,Age,City,State,Income_Bracket,Registration_Year,total_transactions,total_spent,average_purchase,total_sessions,total_pages_visited,total_earned_points,total_redeemed_points
0,C100000,56,Pune,Gujarat,Medium,2025,0.0,0.0,0.0,2.0,36.0,85.0,395.0
1,C100001,46,Nagpur,West Bengal,Low,2025,1.0,3288.0,3288.0,1.0,11.0,1324.0,522.0
2,C100002,32,Kolkata,Rajasthan,High,2022,0.0,0.0,0.0,2.0,32.0,0.0,0.0
3,C100003,25,Nagpur,Karnataka,High,2025,1.0,2048.0,2048.0,1.0,12.0,2399.0,676.0
4,C100004,38,Pune,Tamil Nadu,Medium,2022,1.0,234.0,234.0,1.0,13.0,1350.0,595.0

In [4]:
print("Shape:", feature_data.shape)

Shape: (25000, 13)

In [5]:
print(feature_data.columns.tolist())

['Customer_ID', 'Age', 'City', 'State', 'Income_Bracket', 'Registration_Year', 'total_transactions', 'total_spent', 'average_purchase', 'total_sessions', 'total_pages_visited', 'total_earned_points', 'total_redeemed_points']

In [6]:
feature_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            25000 non-null  object
 1   Age                    25000 non-null  int64
 2   City                   25000 non-null  object
 3   State                  25000 non-null  object
 4   Income_Bracket         25000 non-null  object
 5   Registration_Year      25000 non-null  int64
 6   total_transactions     25000 non-null  float64
 7   total_spent            25000 non-null  float64
 8   average_purchase       25000 non-null  float64
 9   total_sessions         25000 non-null  float64
 10  total_pages_visited    25000 non-null  float64
 11  total_earned_points    25000 non-null  float64
 12  total_redeemed_points  25000 non-null  float64
dtypes: float64(7), int64(2), object(4)
memory usage: 2.5+ MB

In [7]:
feature_data.isnull().sum()

Customer_ID              0
Age                      0
City                     0
State                    0
Income_Bracket           0
Registration_Year        0
total_transactions       0
total_spent              0
average_purchase         0
total_sessions           0
total_pages_visited      0
total_earned_points      0
total_redeemed_points    0
dtype: int64

In [8]:
feature_data.columns.tolist()

['Customer_ID',
 'Age',
 'City',
 'State',
 'Income_Bracket',
 'Registration_Year',
 'total_transactions',
 'total_spent',
 'average_purchase',
 'total_sessions',
 'total_pages_visited',
 'total_earned_points',
 'total_redeemed_points']

In [9]:
clv_features = [
    'total_transactions',
    'total_spent',
    'average_purchase'
]

In [10]:
X = feature_data[clv_features]

In [11]:
feature_data['CLV'] = (
    feature_data['total_spent'] +
    (feature_data['average_purchase'] * feature_data['total_transactions'])
)

In [12]:
feature_data[['Customer_ID', 'total_spent', 'average_purchase',
              'total_transactions', 'CLV']].head()

  Customer_ID  total_spent  average_purchase  total_transactions     CLV
0     C100000          0.0               0.0                 0.0     0.0
1     C100001       3288.0            3288.0                 1.0  6576.0
2     C100002          0.0               0.0                 0.0     0.0
3     C100003       2048.0            2048.0                 1.0  4096.0
4     C100004        234.0             234.0                 1.0   468.0

In [13]:
feature_data['CLV'].describe()

count    25000.000000
mean     10071.070160
std      11599.156165
min          0.000000
25%          0.000000
50%       6729.000000
75%      16879.000000
max      95240.000000
Name: CLV, dtype: float64

In [14]:
X = feature_data[clv_features]
y = feature_data['CLV']

In [15]:
print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (25000, 3)
y Shape: (25000,)

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [18]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (20000, 3)
X_test: (5000, 3)
y_train: (20000,)
y_test: (5000,)

In [19]:
print(y_train.head())

23311    30364.0
23623        0.0
1020         0.0
12645    13698.0
1533     19612.0
Name: CLV, dtype: float64

In [20]:
print("Training CLV Statistics:")
print(y_train.describe())

Training CLV Statistics:
count    20000.000000
mean     10049.346400
std      11636.324171
min          0.000000
25%          0.000000
50%       6657.000000
75%      16834.500000
max      95240.000000
Name: CLV, dtype: float64

In [21]:
from sklearn.ensemble import RandomForestRegressor

In [22]:
clv_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [23]:
clv_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [24]:
y_pred = clv_model.predict(X_test)

In [25]:
print(y_pred[:10])

[    0.   28139.36  9728.06     0.       0.    5576.46 29159.86 11717.12
 34973.92 36700.72]

In [26]:
comparison = pd.DataFrame({
    'Actual_CLV': y_test.values,
    'Predicted_CLV': y_pred
})

comparison.head(10)

   Actual_CLV  Predicted_CLV
0         0.0           0.00
1     28144.0       28139.36
2      9728.0        9728.06
3         0.0           0.00
4         0.0           0.00
5      5578.0        5576.46
6     29156.0       29159.86
7     11718.0       11717.12
8     34976.0       34973.92
9     36692.0       36700.72

In [27]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)
print("Accuracy:", r2 * 100, "%")

R² Score: 0.9999983721586437
Accuracy: 99.99983721586437 %

In [28]:
import joblib

In [29]:
joblib.dump(
    clv_model,
    "../models/clv_model.pkl"
)

['../models/clv_model.pkl']